### ISSUE TITLE
Unable to run the example

### ISSUE THREAD

**Issue by alexmocanu** [SerafimArts/ffi-sdl#2]
I tried running the example provided within the "Usage" section and all I got are these errors:
```
PHP Fatal error:  Uncaught Error: Call to undefined method FFI::init() in C:\Users\alex\Desktop\test_sdl\vendor\serafim\ffi-sdl\src\Support\ProxyTrait.php:153
Stack trace:
#0 C:\Users\alex\Desktop\test_sdl\index.php(9): Serafim\SDL\SDL::__callStatic('init', Array)
#1 {main}
  thrown in C:\Users\alex\Desktop\test_sdl\vendor\serafim\ffi-sdl\src\Support\ProxyTrait.php on line 153

Fatal error: Uncaught Error: Call to undefined method FFI::init() in C:\Users\alex\Desktop\test_sdl\vendor\serafim\ffi-sdl\src\Support\ProxyTrait.php:153
Stack trace:
#0 C:\Users\alex\Desktop\test_sdl\index.php(9): Serafim\SDL\SDL::__callStatic('init', Array)
#1 {main}
  thrown in C:\Users\alex\Desktop\test_sdl\vendor\serafim\ffi-sdl\src\Support\ProxyTrait.php on line 153
```
I enabled the FFI extension in php.ini, then ran the "php -m" command to make sure the extension is available

I installed the composer package with this command: composer require serafim/ffi-sdl
And the composer.json file ended up like this:
```
{
    "require": {
        "serafim/ffi-sdl": "^1.0"
    }
}
```
Here is the php script I'm trying to run:
[index.zip](https://github.com/SerafimArts/ffi-sdl/files/5617591/index.zip)

I tried installing the "dev-master" version but all I got was this error about a composer package that doesn't appear to exist anywhere:
`serafim/ffi-sdl dev-master requires serafim/flux ^1.0 -> could not be found in any version, there may be a typo in the package name.`

Windows 10 Version 20H2 (19042.630)
PHP 7.4.8 (cli) (built: Jul  9 2020 11:30:33) ( NTS Visual C++ 2017 x64 ) downloaded from php.net
Composer 2.0.7

**Comment by SerafimArts** [comment]
Dont use dev-master

**Comment by SerafimArts** [comment]
The error means that there is no such `init` method in the SDL.

When using the 1.x version, you should use the examples from the 1.x version.
